[build]
  command = "python -m pip install --upgrade pip && pip install -r requirements.txt"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.9.16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "python -m pip install --upgrade pip && pip install -r requirements.txt"
